apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-system
  namespace: flux-system
spec:
  template:
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

