apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-demo
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: appdb
      owner: appuser

