apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mydatabase
  namespace: databases
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2.32-bookworm
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: mydatabase
      owner: myuser
